"""
Image Noise Forensics Tool
==========================
Analyses noise patterns in an image to estimate whether it was captured by a
real camera or generated by a diffusion / GAN model.

Usage:
  python main.py path/to/image.jpg
  python main.py photo.png --output ./results --verbose
  python main.py img.webp --no-report
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

from core.loader import load_image
from core.preprocess import preprocess
from core.residual import extract_residuals
from core.features import extract_features
from core.scoring import score_image
from output.visualization import generate_visualizations
from output.report import generate_report
from config import OUTPUT_DIR


_VERDICT_TEXT = {
    "camera":       "CAMERA (real)",
    "synthetic":    "SYNTHETIC (AI-generated)",
    "inconclusive": "INCONCLUSIVE",
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Image Noise Forensics Tool — camera vs AI-generated image analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("image", help="Path to the image file to analyse")
    parser.add_argument(
        "--output", "-o", default=str(OUTPUT_DIR),
        help="Root output directory (default: forensics_output/)"
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Print individual feature scores"
    )
    parser.add_argument(
        "--no-report", action="store_true",
        help="Skip HTML report generation"
    )
    parser.add_argument(
        "--no-visuals", action="store_true",
        help="Skip forensic visualisation images"
    )

    args = parser.parse_args(argv)

    image_path = Path(args.image)
    if not image_path.exists():
        print(f"[ERROR] File not found: {image_path}", file=sys.stderr)
        return 1

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = Path(args.output) / f"{image_path.stem}_{timestamp}"
    out_dir.mkdir(parents=True, exist_ok=True)

    _print(f"Analysing : {image_path}")
    _print(f"Output    : {out_dir}")
    print()

    try:
        _step("1/5", "Loading image")
        image_data = load_image(str(image_path))

        _step("2/5", "Preprocessing")
        processed = preprocess(image_data)

        _step("3/5", "Extracting noise residuals")
        residuals = extract_residuals(processed)

        _step("4/5", "Computing forensic features")
        features = extract_features(image_data, processed, residuals)

        _step("5/5", "Scoring")
        result = score_image(features)

    except Exception as exc:
        print(f"\n[ERROR] Analysis failed: {exc}", file=sys.stderr)
        return 2

    # Visualisations
    if not args.no_visuals:
        try:
            generate_visualizations(processed, residuals, features, out_dir)
        except Exception as exc:
            print(f"[WARN] Visualisation failed: {exc}", file=sys.stderr)

    # Report
    if not args.no_report:
        try:
            generate_report(image_data, processed, features, result, out_dir)
        except Exception as exc:
            print(f"[WARN] Report generation failed: {exc}", file=sys.stderr)

    # Print verdict
    _print_verdict(result, args.verbose)

    if not args.no_report:
        _print(f"\nReport    : {out_dir / 'report.html'}")

    return 0


def _step(num: str, desc: str) -> None:
    print(f"  [{num}] {desc}...")


def _print(msg: str) -> None:
    print(msg)


def _print_verdict(result: dict, verbose: bool) -> None:
    label = result["label"]
    score = result["score"]
    conf = result["confidence"]

    border = "=" * 54
    print(f"\n{border}")
    print(f"  VERDICT    : {_VERDICT_TEXT[label]}")
    print(f"  SCORE      : {score:.4f}   (0=synthetic, 1=camera)")
    print(f"  CONFIDENCE : {conf:.1%}")
    print(border)

    if verbose:
        print("\n  Feature breakdown:")
        for name, val in result["feature_scores"].items():
            filled = int(val * 24)
            bar = "#" * filled + "-" * (24 - filled)
            indicator = "^ cam" if val > 0.62 else ("v syn" if val < 0.38 else "= mid")
            print(f"    {name:<22} [{bar}] {val:.3f}  {indicator}")


if __name__ == "__main__":
    sys.exit(main())
